erda-project/erda-proto

pipeline/queue_usage.proto

related erda pr: https://github.com/erda-project/erda/pull/228

Add proto for pipeline queue usage

---

msp/menu/menu.proto

msp menu apis

---

msp/configcenter/configcenter.proto

config center apis

---

msp/configcenter/configcenter.proto
msp/menu/menu.proto

1、data validate
2、fix config center api path

data validate

---

core/monitor/alert/alert.proto
core/monitor/collector/collector.proto
core/monitor/logs/logs.proto
core/monitor/metric/meta.proto
core/monitor/metric/metric.proto
msp/apm/alert/alert.proto
msp/apm/trace/trace.proto
msp/menu/menu.proto
msp/registercenter/registercenter.proto

1、format proto
2、define metric apis
3、create some files

format proto、define metric apis、create some files

---

core/monitor/alert/alert.proto

feature
modify monitor http to proto

modify monitor http to proto

---

core/monitor/metric/meta.proto
core/monitor/metric/metric.proto
msp/apm/checker/checker.proto
msp/apm/checker/checker_v1.proto

1、checker apis
2、adjust metric apis

checker apis

---

msp/apm/checker/checker_v1.proto

adjust checker apis

---

core/monitor/alert/alert.proto

feature
modify core/monitor alert.proto

modify core/monitor alert.proto

---

msp/apm/alert/alert.proto

feature
modify msp/alert request body

modify msp/alert request body

---

core/monitor/alert/alert.proto
core/monitor/collector/collector.proto
core/monitor/metric/meta.proto
core/monitor/metric/metric.proto
msp/apm/alert/alert.proto
msp/apm/checker/checker_v1.proto

use structpb.Value instead of anypb.Any

use structpb.Value instead of anypb.Any

---

msp/apm/exception/exception.proto

Defined exception API by protobuf

---

core/monitor/metric/metric.proto
msp/apm/checker/checker_v1.proto

change metric api path

---

core/monitor/alert/alert.proto
msp/apm/alert/alert.proto

feature
modify UpdateOrgCustomizeAlertRequest request body

modify UpdateOrgCustomizeAlertRequest

---

msp/resource/resource.proto

1. change status enum name
2. add data field to Response model

bugfix: change resource status enum name

---

core/monitor/metric/metric.proto
msp/apm/checker/checker_v1.proto

general metric query api

---

core/monitor/alert/alert.proto
msp/apm/alert/alert.proto

feature
modify update request body

modify update request body

---

core/monitor/logs/log.proto

log protobuf format for log collect

log format within transfer

---

msp/configcenter/configcenter.proto
msp/registercenter/registercenter.proto

fix config center bug

---

msp/resource/resource.proto

1. add get monitor instance api
2. change getRuntime api name to getMonitorRuntime

feature: add get monitorinstance api

---

msp/apm/alert/alert.proto

feature
modify  CreateAlertRequest

modify  CreateAlertRequest

---

msp/apm/alert/alert.proto

/kind fix
modify url add tenantGroup
@liuhaoyang

modify url add tenantGroup

---

core/monitor/alert/alert.proto

/kind fix
pjy histories limit
@liuhaoyang

pjy histories limit

---

core/monitor/alert/alert.proto

/kind fix
histories limit
@recallsong

histories limit

---

msp/apm/alert/apm_alert.proto

/kind fix
modify GetAlertResponse return fileds
@liuhaoyang

modify GetAlertResponse return fileds

---

core/monitor/alert/alert.proto

/kind fix
modify the url of QueryOrgHostsAlertRecord
@liuhaoyang

modify the url of QueryOrgHostsAlertRecord

---

core/monitor/alert/alert.proto
msp/apm/alert/apm_alert.proto

/kind fix
modify the apm alert fields
@liuhaoyang

modify the apm alert fields

---

msp/apm/trace/trace.proto

Support: query traces by trace_id

---

core/monitor/settings/settings.proto

monitor settings apis

---

core/pipeline/cms/cms.proto

polish field name backward-compatible.

polish: cms proto field backward-compatible

---

core/monitor/alertdetail/details.proto

/kind fix
modify the apm alert fields
@recallsong

add alert_details proto

---

core/monitor/dataview/dataview.proto

monitor dataview

---

common/identity.proto
cp/protocol.proto

feature: add component-protocol

---

common/openapi.proto
examples/greeter.proto
examples/user.proto

1、add openapi option
2、update example

add openapi option

---

core/services/authentication/authentication.proto
core/services/authentication/credentials/accesskey/accesskey.proto

- support pagination access-key
- structure as authentication service

structure & accesskey pagination

---

msp/configcenter/configcenter.proto
msp/registercenter/registercenter.proto

add config center and register center openapi

add config center and register center openapi

---

core/monitor/dataview/dataview.proto
core/monitor/metric/meta.proto
core/monitor/settings/settings.proto
msp/configcenter/configcenter.proto
msp/menu/menu.proto
msp/registercenter/registercenter.proto

update monitor openapi

---

orchestrator/runtime/runtime.proto

Feature/orchestrator-proto-refactor GetRuntime api

---

core/dop/autotest/testplan/autotest-plan.proto

add dop/autotest/testplan proto

---

core/dop/autotest/testplan/autotest-plan.proto

delete V2
delete useless import

fix autotest-plan proto

---

core/pipeline/trigger/trigger.proto

add pipeline_trigger

---

core/pipeline/trigger/trigger.proto

add pipeline trigger openapi

---

core/pipeline/cron/cron.proto

add cron update rpc

---

core/pipeline/base/base.proto
core/pipeline/build/build.proto
core/pipeline/cluster/cluster.proto
core/pipeline/cron/cron.proto
core/pipeline/label/label.proto
core/pipeline/queue/queue.proto
core/pipeline/report/report.proto

use relative path

---

core/dop/autotest/testplan/autotest-plan.proto

add fields in autotest-plan

---

msp/apm/checker/checker_v1.proto

add openapi checker

---

core/pipeline/cron/cron.proto

modify get cron method

---

core/dop/autotest/testplan/autotest-plan.proto

https://github.com/erda-project/erda-proto/pull/167
cherry-pick release/1.3

release/1.3 update autotest-plan content
